### ISSUE TITLE
Add AI/LLM-compatible metadata generation to asset packages

### ISSUE THREAD

**Issue by docdann** [docdann/assetkit#37]
Add support for generating structured metadata alongside each asset in an AssetKit package. This metadata will describe the asset’s content, format, intended use, schema (for JSON/YAML), and tags — enabling LLMs or agent frameworks to reason about and use assets programmatically.

- [ ]  Add assetkit.metadata module for asset introspection and schema inference

Auto-generate assetkit.yaml with an assets: section describing each asset:

```yaml
assets:
  config_model_yaml:
    path: resources/assets/config/model.yaml
    format: yaml
    schema:
      type: object
      properties:
        model_name: { type: string }
        layers: { type: array }
    tags: [config, model]
  image_tar:
    path: resources/assets/image.tar
    format: docker-tar
    tags: [docker, container]
```
- [ ]  Support extensible format plugins for new asset types (e.g. .csv, .jsonl, .onnx)

- [ ]  CLI command: assetkit inspect <package> — prints metadata in human-friendly format

- [ ]  Allow manual annotations via YAML overlay (assetkit.meta.yaml)

- [ ]  Optional export to JSON Schema, JSON-LD, or LLM-readable Markdown

Benefits:
